DROP TABLE PEGAWAI CASCADE CONSTRAINT PURGE;
DROP TABLE JENIS_BARANG CASCADE CONSTRAINT PURGE;
DROP TABLE SUPPLIER CASCADE CONSTRAINT PURGE;
DROP TABLE SUPPLIER_KONSINYASI CASCADE CONSTRAINT PURGE;
DROP TABLE NOTA_BELI CASCADE CONSTRAINT PURGE;
DROP TABLE JENIS_MEMBER CASCADE CONSTRAINT PURGE;
DROP TABLE MEMBER CASCADE CONSTRAINT PURGE;
DROP TABLE AREA CASCADE CONSTRAINT PURGE;
DROP TABLE PENGIRIMAN CASCADE CONSTRAINT PURGE;
DROP TABLE NOTA_JUAL CASCADE CONSTRAINT PURGE;
DROP TABLE BARANG CASCADE CONSTRAINT PURGE;
DROP TABLE TRANSAKSI_SUPPLIER_KONSINYASI CASCADE CONSTRAINT PURGE;
DROP TABLE TRANSAKSI_BARANG_KONSINYASI CASCADE CONSTRAINT PURGE;
DROP TABLE NOTA_JUAL_BARANG CASCADE CONSTRAINT PURGE;
DROP TABLE NOTA_BELI_BARANG CASCADE CONSTRAINT PURGE;
DROP TABLE PROMO CASCADE CONSTRAINT PURGE;
DROP TABLE AREA_PENGIRIMAN CASCADE CONSTRAINT PURGE;

CREATE TABLE PEGAWAI
(
	ID_PEGAWAI CHAR(8) PRIMARY KEY,
	NAMA_PEGAWAI VARCHAR2(50) NOT NULL,
	UMUR_PEGAWAI NUMBER(6) NOT NULL,
	ALAMAT_PPEAGAWAI VARCHAR2(50) NOT NULL,
	JABATAN_PEGAWAI VARCHAR2(20)  NOT NULL,
	GENDER_PEGAWAI CHAR(2) CHECK (GENDER_PEGAWAI = 'P' OR GENDER_PEGAWAI = 'L')
);

CREATE TABLE JENIS_BARANG
(
	ID_JENIS_BARANG CHAR(8) PRIMARY KEY,
	NAMA_JENIS_BARANG VARCHAR2(50)
);

CREATE TABLE SUPPLIER
(
	ID_SUPPLIER CHAR(8) PRIMARY KEY,
	NAMA_SUPPLIER VARCHAR2(50) NOT NULL,
	NO_TELEPON_SUPPLIER NUMBER(13) NOT NULL,
	ALAMAT_SUPPLIER VARCHAR2(50) NOT NULL
);

CREATE TABLE SUPPLIER_KONSINYASI
(
	ID_SUPPLIER_KONSINYASI CHAR(8) PRIMARY KEY,
	NAMA_SUPPLIER_KONSINYASI VARCHAR2(50),
	NO_TELEPON_SUPPLIER_KONSINYASI NUMBER(13)
);

CREATE TABLE NOTA_BELI
(
	ID_NOTA_BELI CHAR(8) PRIMARY KEY,
	ID_PEGAWAI CHAR(8) REFERENCES PEGAWAI(ID_PEGAWAI),
	ID_SUPPLIER CHAR(8) REFERENCES SUPPLIER(ID_SUPPLIER),
	TANGGAL_NOTA_BELI DATE,
	STATUS_PEMBAYARAN VARCHAR2(20),
	TANGGAL_PEMBAYARAN DATE, 	
	TENGGANG_PEMBAYARAN DATE
);

CREATE TABLE JENIS_MEMBER
(
	ID_JENIS_MEMBER CHAR(8) PRIMARY KEY,
	NAMA_JENIS_MEMBER VARCHAR2(50) NOT NULL,
	MINIMAL_JUMLAH_HARGA_PEMBELIAN NUMBER(10) NOT NULL,
	DISKON NUMBER(5)
);

CREATE TABLE MEMBER
(
	ID_MEMBER CHAR(8) PRIMARY KEY,
	ID_JENIS_MEMBER CHAR(8) REFERENCES JENIS_MEMBER(ID_JENIS_MEMBER),
	NAMA_MEMBER VARCHAR2(50) NOT NULL,
	NO_TELEPON_MEMBER NUMBER(13) NOT NULL,
	GENDER_MEMBER CHAR(2) CHECK (GENDER_MEMBER = 'P' OR GENDER_MEMBER = 'L')
);

CREATE TABLE AREA
(
	ID_AREA CHAR(8) PRIMARY KEY,
	AREA_KIRIM VARCHAR2(50) NOT NULL,
	ONGKOS_KIRIM NUMBER(10) NOT NULL
);

CREATE TABLE PENGIRIMAN
(
	ID_PENGIRIMAN CHAR(8) PRIMARY KEY,
	ID_MEMBER CHAR(8) REFERENCES MEMBER(ID_MEMBER),
	ALAMAT_PENGIRIMAN CHAR(50) NOT NULL
);

CREATE TABLE NOTA_JUAL
(
	ID_NOTA_JUAL CHAR(8) PRIMARY KEY,
	ID_MEMBER CHAR(8) REFERENCES MEMBER(ID_MEMBER),
	ID_PENGIRIMAN CHAR(8) REFERENCES PENGIRIMAN(ID_PENGIRIMAN),
	ID_PEGAWAI CHAR(8) REFERENCES PEGAWAI(ID_PEGAWAI),
	TANGGAL_NOTA_JUAL DATE NOT NULL
);

CREATE TABLE BARANG
(
	ID_BARANG CHAR(8) PRIMARY KEY,
	ID_JENIS_BARANG CHAR(8) REFERENCES JENIS_BARANG(ID_JENIS_BARANG),
	NAMA_BARANG VARCHAR2(50) NOT NULL,
	HARGA_SATUAN NUMBER(10) NOT NULL,
	HARGA_MULTI_SATUAN NUMBER(10),
	KONVERSI_SATUAN NUMBER(3),
	STOK_BARANG NUMBER(10),
	MINIMAL_STOK NUMBER(10) NOT NULL,
	TANGGAL_KADALUARSA DATE
);

CREATE TABLE TRANSAKSI_SUPPLIER_KONSINYASI
(
	ID_TRANSAKSI_KONSINYASI CHAR(8) PRIMARY KEY,
	ID_SUPPLIER_KONSINYASI CHAR(8) REFERENCES SUPPLIER_KONSINYASI(ID_SUPPLIER_KONSINYASI),
	HARGA_BARANG_KONSINYASI NUMBER(10),
	BANYAK_BARANG_KONSINYASI NUMBER(3)
);

CREATE TABLE TRANSAKSI_BARANG_KONSINYASI
(
	ID_BARANG CHAR(8) REFERENCES BARANG(ID_BARANG),
	ID_TRANSAKSI_KONSINYASI CHAR(8) REFERENCES TRANSAKSI_SUPPLIER_KONSINYASI(ID_TRANSAKSI_KONSINYASI),
	CONSTRAINT PK_TRANSAKSI_BARANG_KONSINYASI PRIMARY KEY(ID_BARANG,ID_TRANSAKSI_KONSINYASI)
);

CREATE TABLE NOTA_JUAL_BARANG
(
	ID_NOTA_JUAL CHAR(8) REFERENCES NOTA_JUAL(ID_NOTA_JUAL),
	ID_BARANG CHAR(8) REFERENCES BARANG(ID_BARANG),
	BANYAK_BARANG_TERJUAL NUMBER(3),
	CONSTRAINT PK_BARANG_NOTA_JUAL PRIMARY KEY(ID_NOTA_JUAL,ID_BARANG)
);

CREATE TABLE NOTA_BELI_BARANG
(
	ID_NOTA_BELI CHAR(8) REFERENCES NOTA_BELI(ID_NOTA_BELI),
	ID_BARANG CHAR(8) REFERENCES BARANG(ID_BARANG),
	BANYAK_BARANG_BELI NUMBER(3),
	HARGA_POKOK_BARANG NUMBER(10) NOT NULL,
	CONSTRAINT PK_NOTA_BELI_BARANG PRIMARY KEY(ID_NOTA_BELI,ID_BARANG)
);

CREATE TABLE PROMO
(
	ID_PROMO CHAR(8) PRIMARY KEY,
	ID_BARANG CHAR(8) REFERENCES BARANG(ID_BARANG),
	TANGGAL_AWAL_PROMO DATE NOT NULL,
	TANGGAL_AKHIR_PROMO DATE NOT NULL,
	NAMA_PROMO VARCHAR2(50) NOT NULL,
	BESAR_PROMO NUMBER (10) NOT NULL
);

CREATE TABLE AREA_PENGIRIMAN
(
	ID_AREA CHAR(8) REFERENCES AREA(ID_AREA),
	ID_PENGIRIMAN CHAR(8) REFERENCES PENGIRIMAN(ID_PENGIRIMAN),
	CONSTRAINT PK_AREA_PENGIRIMAN PRIMARY KEY(ID_AREA,ID_PENGIRIMAN)
);